---
env:
  browser: true
  jest/globals: true

extends:
- standard
- plugin:react/recommended

plugins:
- jest

parserOptions:
  ecmaVersion: 11
  impliedStrict: true
  ecmaFeatures:
    jsx: true
  sourceType: module

rules:
  yoda:
    - 2
    - never
    - onlyEquality: true
