---
env:
  browser: true

extends:
- standard
- plugin:react/recommended

parserOptions:
  ecmaVersion: 11
  impliedStrict: true
  ecmaFeatures:
    jsx: true
  sourceType: module

rules:
  yoda:
    - 2
    - never
    - onlyEquality: true
